sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - jar_artifact
linkReplacements:
  - "https://www.mojohaus.org/flatten-maven-plugin/flatten-maven-plugin|https://www.mojohaus.org/flatten-maven-plugin/"
