sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - jar_artifact
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_upload_github_release_assets.yml'"
