sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - jar_artifact
build:
  runnerOs: ubuntu-latest
  freeDiskSpace: false
  exasolDbVersions:
    - "8.32.0"
    - "7.1.30"
