language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol
    token:
      secure: fdJKDyPBDQPgG/+AUvkgItkoo9e78eccEJLJxbkOTFtv595L+wt0HadvnZKWOeT+OejxL+ZfVvqMPFlBjkyBSO67YuMmD1L6c0iFQPFx3x8VZxZdjvkmfw5ch3z6ah/GawOd1la9Xd1K3vmbc40Y7zAai8Iz1+2nX5LBhgYOZtCwQ/twir+WEaSAGJ7Om/03zBlOd2yH5xgJXPzYVD5ya+72YWvvEOCuSD9UQgZP5gyZkQkjjis+yk8KqwQv+6utE1ZaipDeDzqI0wLaX3Qwu74gCXWRSJIcR3gX/TQU6Db7O3HM4VwfquwrFs1qJ5TcjUtJdjnnCb6zzbFWPR30v/5DatsccRdrNSdDaoPyE93fdgAmoOxZM/pmQBy4ZXmwRKuDKEQzqakckkSQhoTWhYkgaT34pjWKl1EVtxtg+d+4YmqLq1+SIC/v3bsy1c052TkXsiL0UXKTmy48s0KmVmvAhJ/k9O/YwzN/VWiiiY+xqRe3R3+qH/Gw5fDqUCccFS4+QqZm8ByayKj2oPvV7dj14B2aCSYPzAC96SpTk9+uzy4xlKRb/n1sPCYFuXIxwT6rMpn+imeREZqvoYbcl8Sjh1m90MyH6fCbhxHUCp46eUzezPC1SiB7AoJd9e7/tCFZomntNmZ0YTq55wRcw0Pels6pc+qWUmBH7lhG7e0=

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2"