language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol
    token:
      secure: "ZUUNy5Fc7M2rpfvVmaAxltQP7AI8f5LlU/DVx9uTla62zd8WFRuzzzTWoIRoZMe7GxPe9BdgEE0s1mgkve07Os7QDue9SFetNCxFh/bWuil9Apw8D1FC8juxcGdJ9YFBzm2Yao0zLfj8vPhKWNUF3u8dfebutST4dAaj8a+QT/QZnp6PRvCN2eHxfKR7DfEw/K7ATvOqDP7AmapuaQgWHaNOwrPlpwjyQSLj25kTXUNK/R+guygZVxlw0x+JqWJ2QmqotqeFG5K9hW0JaXs47OrD573WYqlDJw4mBskceZtODFLzCMg22B7DgMyG8DImivgi02UtcNHuZeNXc8CNnrbeusxo7DxKTTp1G5JTUrFfDPzYsSvbpbJaXI5xMbwC4Fb6fMi7A8mPKw/+QHl3gIZ9ou6HOUCGwFaK6Vx7rhrs9zBkK3YoRgRNMqoD7QhV/s+YV/rQiyIFdnLYcX440PL5fvmx1q2FTU7jcwdXtr4bHHyfPayuFtio/q0E/XhflRx1VcxyMZG+ToJPZQPd9MudjtTE0TsKgBAcQAblux5ciG0ZEepVDpYlW5azmRPecYxleB8+LtjkAWsdagMIqp6l/i1/wmZMubXsQXR0FxWd8s0+J5p0mG2YzY3tG0whR56G7FDXHQw1pnyEV8mj5tEhXLqVm6ArYXgfsYSuRFg="

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2"