name: Build Native Images
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build native-image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: macos-latest
            suffix: -mac-x86
          - os: windows-latest
            suffix: .exe
          - os: ubuntu-latest
            suffix: -linux-x86
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '21.2.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests for native image builds
        run: |
          mvn --batch-mode clean package "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn" -DtrimStackTrace=false -DskipTests "-Dmaven.test.skip=true" "-Dproject-keeper.skip=true" "-Dossindex.skip=true" "-Dmaven.javadoc.skip=true" "-Djacoco.skip=true" "-Dreproducible.skip=true"
          native-image --verbose -jar target/*.jar target/bfsc${{ matrix.suffix }}
          dir target
          mvn test -D"native.binary=bin-${{ matrix.os }}" -D"org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn" -DtrimStackTrace=false -P native-image -Dtest=NativeImageTest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: bfsc${{ matrix.suffix }}
          path: target/bfsc${{ matrix.suffix }}
          if-no-files-found: error
