name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Assets upload URL'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Build with Maven skipping tests
        run: mvn --batch-mode clean verify -DskipTests "-Dproject-keeper.skip=true"
      - name: Generate sha256sum files Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd target
          $file = (dir target -Filter bfsc-*.jar).Name.TrimEnd('.jar')
          (Get-FileHash $file.jar -Algorithm SHA256).Hash.ToLower() > $file.sha256
          (Get-FileHash  bfsc.exe -Algorithm SHA256).Hash.ToLower() >  bfsc.exe.sha256
      - name: Generate sha256sum files Ubuntu and MacOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          cd target
          file=$(basename -- bfsc-*.jar)
          file=${file%.*}
          sha256sum $file.jar > $file.sha256 # jar file
          sha256sum bfsc > bfsc.sha256 # native executable
      - name: Upload assets to the GitHub release draft
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.jar
      - name: Upload sha256sum files
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.sha256
      - name: Upload error-code-report
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/error_code_report.json
